### ISSUE TITLE
[QUESTION] Clearing Cookies based on Matched Rules

### ISSUE THREAD

**Issue by samgavinio** [FriendsOfSymfony/FOSHttpCache#250]
Is there a way to do the following in the `fos_http_cache` configuration in the `config.yml` of my application? 
```
sub vcl_recv {
   if(req.url ~  "^/foo/bar$"){
       unset req.http.cookie;
   }
}
```
This clears the cookie for a certain URL so that it can be cached. Symfony2 creates a session almost by default so a cookie is always present making most pages uncacheable so most would advise to unset the header of not very dynamic resources/pages.

This would normally reside in our varnish vcl file. However, I hate the fact that this file isn't versioned along with my application. 

What I would like to do is include it the bundle configuration somewhere in here:

```

fos_http_cache:
    proxy_client:
        varnish:
            servers: 127.0.0.1:80
            base_url: www.foo.bar
    cache_control:
        defaults:
            overwrite: false
        rules:
            -
                match:
                    host: ^/foo/bar$
                headers:
                    overwrite: true
                    cache_control:
                        public: false
                        max_age: 600
                        s_maxage: 0
                    etag: true
                    vary: [Accept-Encoding, Accept-Language]

```

Is there a configuration I can use for this?
