### ISSUE TITLE
What is the correct config for a dev environment

### ISSUE THREAD

**Issue by jakenoble** [FriendsOfSymfony/FOSHttpCache#345]
My use case seems simple enough - have the following code work on prod and ignored on dev

```
$cacheManager = $this->get('fos_http_cache.cache_manager');
$cacheManager->invalidatePath($path)->flush();
```

But I get this error 
_The service "app.parser" has a dependency on a non-existent service "fos_http_cache.cache_manager"._

When using this config for my dev env;

```
fos_http_cache:
    cache_manager:
        enabled: false
    invalidation:
        enabled: false
```

I have not found anything in the docs about how to config the development environment to correctly ignore Varnish or any other cache.

I see there is a Noop Class, which seems perfect - but no docs on how to use this and all my attempts to use it via Symfony's config have failed.
